version: "3.9"
services:
  db:
    image: postgres:16
    container_name: challenge_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge_db
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro