version: "3.9"
services:
  db:
    image: postgres:16
    container_name: challenge_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # poner esto en un .env y un gitignore
      POSTGRES_DB: challenge_db
    ports:
      - "5001:5432"
    volumes:
      - challenge_db:/var/lib/postgresql/data


volumes:
  challenge_db: